### ISSUE TITLE
Supervisor page is no longer dark after updating supervisor to 231

### ISSUE THREAD

**Issue by ArgoHA** [seangreen2/slate_theme#15]
Hi! I have copied your theme code from github and made couple of changes for myself. Now I have updated supervisor to 231 and now supervisor page is default themed

<img width="1595" alt="Снимок экрана 2020-08-12 в 13 09 19" src="https://user-images.githubusercontent.com/43640256/90003670-12b43e80-dc9d-11ea-980e-c94cf0421281.png">

Here is my code with slight changes (last 3 lines). There is no way that changes can effect anything on supervisor page :)

```
slate_moded:
  # Main colors
  primary-color: '#2980b9'
  # accent-color: '#2980b9'
  dark-primary-color: '#2980b9'
  light-primary-color: '#2980b9'
  # Text colors
  primary-text-color: '#FFFFFF'
  text-primary-color: 'var(--primary-text-color)'
  # secondary-text-color: '#b58e31'
  disabled-text-color: '#777777'
  label-badge-border-color: 'green'
  # Sidebar
  sidebar-icon-color: '#777777'
  # Background colors
  primary-background-color: '#222222'
  secondary-background-color: '#222222'
  divider-color: 'rgba(0, 0, 0, .12)'
  table-row-background-color: '#292929'
  table-row-alternative-background-color: '#292929'
  # Nav Menu
  paper-listbox-color: '#777777'
  paper-listbox-background-color: '#141414'
  paper-grey-50: 'var(--primary-text-color)'
  paper-grey-200: '#222222'
  # Paper card
  paper-card-header-color: '#2980b9'
  paper-card-background-color: '#292929'
  paper-dialog-background-color: '#292929'
  paper-item-icon-color: 'var(--primary-text-color)'
  paper-item-icon-active-color: '#b58e31'
  paper-item-icon_-_color: 'green'
  paper-item-selected_-_background-color: '#292929'
  paper-tabs-selection-bar-color: 'green'
  # Labels
  # label-badge-red: 'var(--primary-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  label-badge-background-color: '#222222'
  # Switches
  paper-toggle-button-checked-button-color: '#2980b9'
  paper-toggle-button-checked-bar-color: '#2980b9'
  paper-toggle-button-checked-ink-color: '#2980b9'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
  switch-checked-color: 'var(--paper-toggle-button-checked-button-color)'
  switch-unchecked-color: 'var(--disabled-text-color)'
  switch-unchecked-button-color: 'var(--disabled-text-color)'
  switch-unchecked-track-color: 'var(--disabled-text-color)'
  # Sliders
  paper-slider-knob-color: '#2980b9'
  paper-slider-knob-start-color: '#2980b9'
  paper-slider-pin-color: '#2980b9'
  paper-slider-active-color: '#2980b9'
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
  # Google colors
  google-red-500: '#b93829'
  google-green-500: '#2980b9'
  # Changes to fix history/logbook menus
  lumo-primary-text-color: '#2980b9'
  lumo-secondary-text-color: '#2980b9'
  lumo-primary-color: '#2980b9'
  # Calendar day numbers
  lumo-body-text-color: '#b58e31'
  # Calendar/Date-Picker Background
  lumo-base-color: '#222222'
  # Month/Year header
  lumo-header-text-color: 'var(--lumo-body-text-color)'
  # DayOfWeek Header
  lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
  lumo-shade: '#222222'
  lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
  lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
  lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
  lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
  lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
  lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
  lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
  lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
  lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
  lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
  lumo-tint-5pct: '#222222'
  # fix for device configuration screen
  card-background-color: "var(--paper-card-background-color)"
  # Fix for Person Device Chooser - thanks to vajonam!
  material-background-color: "var(--paper-listbox-background-color)"
  material-secondary-background-color: '#222222'
  material-body-text-color: '#FFFFFF'
  # simple-thermostat buttons
  st-mode-background: 'var(--primary-background-color)'
  # fix white on white markdown code sections (eg. the addons infos)
  markdown-code-background-color: 'var(--secondary-background-color)'

# custom badges
  label-badge-red: '#2c6e9a'

  accent-color: '#2980b9'
  secondary-text-color: '#a8a8a8'
```
