### ISSUE TITLE
Entities in status off and unavailable look the same

### ISSUE THREAD

**Issue by parautenbach** [seangreen2/slate_theme#16]
It seems like the theme isn't making a distinction between an entity that's off vs unavailable. See the black icon (garage button) on my default theme. Is this a bug and is there a workaround in the meantime?

![IMG_3417](https://user-images.githubusercontent.com/743320/103092972-ac9fd680-4601-11eb-8f6f-78614a2de986.PNG)
![IMG_3418](https://user-images.githubusercontent.com/743320/103092978-b1648a80-4601-11eb-8a03-cf25d451b9b5.PNG)

**Comment by seangreen2** [comment]
What kind of lovelace cards are those that have this problem? Something custom?
When something is Unavailable the colors should change from white to a darker gray color.

**Comment by parautenbach** [comment]
I'll investigate further on that front. I'm using the Custom Button Card here. 

Which CSS variable defines the unavailable colour?

**Comment by parautenbach** [comment]
I at last got around investigating this properly. 

There is no problem with the theme. 

The `custom:button-card` that I'm using requires me to specify the colour when it's unavailable. 

In case anybody else comes across this, you need to set the state like this if you also specify `color:` at the top-level.

```
  - type: custom:button-card
    name: My Light
    entity: light.my_light
    color: var(--button-card-light-color)
    ...
    state:
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)

```
